import type { CategoryID } from './categories.data'
import type { PropertyID } from './properties.data'

export type PropertyWithReason = {
	id: PropertyID
	reason: string
}

// TODO: bring the missing reasons to ZERO

export const CATEGORY_PROPERTIES: Record<CategoryID, PropertyWithReason[]> = {
	'0': [
		{ id: 'preadditive', reason: 'This is vacuously true.' },
		{ id: 'discrete', reason: 'trivial' },
		{ id: 'binary products', reason: 'This is vacuously true.' },
		{ id: 'finite', reason: 'trivial' },
	],
	'1': [
		{ id: 'trivial', reason: 'trivial' },
		{ id: 'finite', reason: 'trivial' },
		{ id: 'discrete', reason: 'trivial' },
	],
	'2': [
		{ id: 'discrete', reason: 'trivial' },
		{ id: 'finite', reason: 'trivial' },
		{ id: 'inhabited', reason: 'trivial' },
	],
	'Set': [
		{ id: 'locally small', reason: 'The collection of maps between two sets $X,Y$ is a subset of $X \\times Y$ and therefore a set.' },
		{ id: 'Grothendieck topos', reason: 'It is equivalent to the category of sheaves on a one-point space.' },
		{ id: 'finitary algebraic', reason: 'Use the empty algebraic theory.' },
	],
	'Ab': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Ab} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'abelian', reason: 'standard' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a commutative group.' },
	],
	'Top': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Top} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'complete', reason: 'Take the limit of the underlying sets and endow it with the coarsest topology making all projections continuous.' },
		{ id: 'cocomplete', reason: 'Take the colimit of the underlying sets and endow it with the finest topology making all inclusions continuous.' },
		{ id: 'well-powered', reason: 'This is clear from the classification of monomorphisms as injective continuous maps.' },
		{ id: 'well-copowered', reason: 'This is clear from the classification of epimorphisms as surjective continuous maps.' },
		{ id: 'infinitary distributive', reason: 'The canonical continuous map $\\coprod_i (X \\times Y_i) \\to X \\times \\coprod_{i \\in I} Y_i$ is bijective since $\\mathbf{Set}$ is infinitary distributive, and one easily checks with the definitions of product and coproduct topologies that it maps open sets to open sets.' },
		{ id: 'generator', reason: 'The one-point space is a generator since it represents the forgetful functor $\\mathbf{Top} \\to \\mathbf{Set}$.' },
		{ id: 'disjoint coproducts', reason: 'This follows easily from the corresponding fact for sets.' },
	],
	'Grp': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Grp} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'pointed', reason: 'The trivial group is a zero object.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a group.' },
		{ id: 'mono-regular', reason: 'See Prop. 4.2 at the <a href="https://ncatlab.org/nlab/show/regular+monomorphism#Examples" target="_blank">nLab</a>.' },
		{ id: 'disjoint coproducts', reason: 'It follows from the normal form of the elements of coproducts of groups that the inclusions $G \\to G \\sqcup H \\leftarrow H$ are injective (hence, monomorphisms) and that their intersection is trivial.' },
		{ id: 'epi-regular', reason: 'This holds since every epimorphism is surjective, and surjective homomorphism $A \\to B$ is the coequalizer of its kernel pair $A \\times_B A \\rightrightarrows A$.' },
		{ id: 'Malcev', reason: 'easy; see also Borceux & Bourn (2004), Ex. 2.2.4' },
	],
	'Vect': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Vect} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'split abelian', reason: 'It is a fact from linear algebra that every subspace has a complement.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a vector space.' },
	],
	'Ring': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Ring} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a ring.' },
		{ id: 'strict terminal object', reason: 'If $f : 0 \\to R$ is a homomorphism, then $R$ satisfies $1=f(1)=f(0)=0$, so that $R=0$.' },
		{ id: 'Malcev', reason: 'follows in the same way as for (additive) groups' },
	],
	'CRing': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{CRing} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a commutative ring.' },
		{ id: 'strict terminal object', reason: 'If $f : 0 \\to R$ is a homomorphism, then $R$ satisfies $1=f(1)=f(0)=0$, so that $R=0$.' },
		{ id: 'Malcev', reason: 'follows in the same way as for (additive) groups' },
	],
	'Rng': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Rng} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of a rng.' },
		{ id: 'pointed', reason: 'The zero ring is a zero object.' },
		{ id: 'disjoint coproducts', reason: 'The coproduct of two rngs $R,S$ has as underlying additive group $R \\oplus S \\oplus (R \\otimes S) \\oplus (S \\otimes R) \\oplus \\cdots$ from which the claim easily follows.' },
		{ id: 'Malcev', reason: 'follows in the same way as for (additive) groups' },
	],
	'FinSet': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{FinSet} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'essentially small', reason: 'Every finite set is isomorphic to some $[n] = \\{1,\\dotsc,n\\}$ for some $n \\in \\mathbb{N}$.' },
		{ id: 'elementary topos', reason: 'This follows easily from the fact that sets form an elementary topos.' },
		{ id: 'generator', reason: 'The one-point set is a generator since it represents the forgetful functor $\\mathbf{FinSet} \\to \\mathbf{Set}$.' },
		{ id: 'cogenerator', reason: 'The two-element set is a cogenerator.' },
	],
	'FinAb': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{FinAb} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'essentially small', reason: 'The underlying set of a finite structure can be chosen to be a subset of $\\mathbb{N}$.' },
		{ id: 'abelian', reason: 'follows from the fact for abelian groups' },
		{ id: 'self-dual', reason: 'Pontrjagin duality' },
	],
	'Abfg': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{FinAb} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'essentially small', reason: 'Every finitely generated abelian group is isomorphic to a group of the form $\\mathbb{Z}^n / U$, where $n \\in \\mathbb{N}$ and $U$ is a subgroup of $\\mathbb{Z}^n$. And these constitute a set.' },
		{ id: 'abelian', reason: 'This follows from the fact for abelian groups and the fact that subgroups of finitely generated abelian groups are also finitely generated.' },
		{ id: 'generator', reason: 'The group $\\mathbb{Z}$ is a generator since it represents the forgetful functor $\\mathbf{Abfg} \\to \\mathbf{Set}$.' },
	],
	'Set*': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Set}_* \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'pointed', reason: 'The singleton set is a zero object.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory with just one constant.' },
		{ id: 'subobject classifier', reason: 'The pointed set $(\\{0,1\\},1)$ is a subobject classifier.' },
		{ id: 'cogenerator', reason: 'The pointed set $(\\{0,1\\},1)$ is a cogenerator.' },
		{ id: 'disjoint coproducts', reason: 'Follows easily from the description of coproducts as wedge sums.' },
		{ id: 'epi-regular', reason: 'Every epimorphism is surjective for this category, and in an algebraic category every surjective homomorphism is a regular epimorphism.' },
	],
	'sSet': [
		{ id: 'locally small', reason: 'This follows from the general fact that $[\\mathcal{C},\\mathcal{D}]$ is locally small when $\\mathcal{C}$ is small and $\\mathcal{D}$ is locally small, here applied to $\\mathcal{C} = \\Delta^{\\mathrm{op}}$ and $\\mathcal{D} = \\mathbf{Set}$.' },
		{ id: 'Grothendieck topos', reason: 'obvious' },
		{ id: 'locally finitely presentable', reason: 'The free cocompletion of a small category is clearly locally finitely presentable.' },
	],
	'Mon': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Mon} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'pointed', reason: 'The trivial monoid is a zero object.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic of a monoid.' },
		{ id: 'disjoint coproducts', reason: 'It follows from the normal form of the elements of coproducts of monoids that the inclusions $G \\to G \\sqcup H \\leftarrow H$ are injective (hence, monomorphisms) and that their intersection is trivial.' },
	],
	'Pos': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Pos} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'locally finitely presentable', reason: 'See <a href="https://ncatlab.org/nlab/show/Locally+Presentable+and+Accessible+Categories" target="_blank">Adamek-Rosicky</a>, Example 1.10.' },
		{ id: 'cartesian closed', reason: 'For partial orders $P,Q$ we endow $\\hom(P,Q)$ with the partial order in which $f \\leq g$ holds iff $f(p) \\leq g(p)$ for all $p \\in P$. The universal evaluation map is $\\hom(P,Q) \\times P \\to Q$, $(f,p) \\mapsto f(p)$, it is order-preserving, and it satisfies the universal property.' },
		{ id: 'cogenerator', reason: 'We prove that the poset $\\{0 < 1 \\}$ is a cogenerator: Let $P$ be a poset and $a,b \\in P$ be two elements such that $f(a) = f(b)$ for all order-preserving maps $f : P \\to \\{0 < 1 \\}$. This means that $a$ and $b$ lie in the same upper sets. In particular, $b$ lies in the upper set generated by $a$, meaning %$a \\leq b$, and similarly we deduce $b \\leq a$. Thus, $a = b$.' },
		{ id: 'disjoint coproducts', reason: 'This follows easily from the corresponding fact for sets, since the coproduct of posets is built using the disjoint union.' },
	],
	'walking_morphism': [
		{ id: 'finite', reason: 'trivial' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory with no operations but with the equation $x=y$ that is supposed to hold for all elements $x,y$. The algebras for this theory are the empty set and the singleton set, hence we get the equivalence to $\\{0 \\to 1\\}$.' },
		{ id: 'self-dual', reason: 'trivial' },
		{ id: 'infinitary distributive', reason: 'Clearly, this category is (co)complete. Also, the functors $X \\mapsto X \\times 1 = X$ and $X \\mapsto X \\times 0 = 0$ are clearly cocontinuous.' },
		{ id: 'skeletal', reason: 'The two objects are not isomorphic' },
	],
	'M-Set': [
		{ id: 'locally small', reason: 'There is a forgetful functor $M{-}\\mathbf{Set} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of an $M$-sets (having a unary operation for each $m \\in M$).' },
		{ id: 'Grothendieck topos', reason: 'It is the category of sheaves on the opposite of the one-object category associated to $M$.' },
	],
	'R-Mod': [
		{ id: 'locally small', reason: 'There is a forgetful functor $R{-}\\mathbf{Mod} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'abelian', reason: 'standard' },
		{ id: 'finitary algebraic', reason: 'Take the algebraic theory of an $R$-module (given by the algebraic theory of an abelian group and for each $r \\in R$ a unary operation).' },
	],
	'Met': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Met} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'well-powered', reason: 'This follows since monomorphisms are injective.' },
		{ id: 'equalizers', reason: 'Just restrict the metric to the equalizer built from the sets.' },
		{ id: 'terminal object', reason: 'The one-point metric space is terminal.' },
		{ id: 'binary products', reason: 'The product of two metric spaces $(X,d)$, $(Y,d)$ is $(X \\times Y,d)$ with $d((x_1,y_1),(x_2,x_2)) := \\sup(d(x_1,x_2),d(y_1,y_2))$.' },
		{ id: 'coequalizers', reason: '' },
		{ id: 'filtered colimits', reason: 'Given a filtered diagram $(X_i)$ of metric spaces, take the filtered colimit $X$ of the underlying sets with the following metric: If $x,y \\in X$, let $d(x,y)$ be infimum of all $d(x_i,y_i)$, where $x_i,y_i \\in X_i$ are some preimages of $x,y$ in some $X_i$. This is only a pseudo-metric, so finally take the associated metric space (Kolmogorov quotient). The definition ensures that each $X_i \\to X$ is non-expansive, and the universal property is easy to check.' },
		{ id: 'strict initial object', reason: 'easy since the initial object is the empty metric space' },
		{ id: 'generator', reason: 'The one-point metric space is a generator since it represents the forgetful functor $\\mathbf{Met} \\to \\mathbf{Set}$.' },
		{ id: 'cogenerator', reason: 'We claim that $\\mathbb{R}$ with the usual metric is a cogenerator. Let $a,b \\in X$ be two points of a metric space such that $f(a)=f(b)$ for all non-expansive maps $f : X \\to \\mathbb{R}$. This applies in particular to $f(x) := d(a,x)$ and shows that $0=d(a,a)=d(a,b)$, so that $a=b$.' },
	],
	'Met_oo': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Met}_{\\infty} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'locally ℵ₁-presentable', reason: 'Example 4.5 in <a href="https://arxiv.org/abs/1504.02660" target="_blank">this preprint</a>' },
		{ id: 'infinitary distributive', reason: 'This follows from the corresponding fact for topological spaces. Here, the coproduct metric takes value $\\infty$ for points in distinct spaces.' },
		{ id: 'cogenerator', reason: 'The proof is similar to $\\mathbf{Met}$, a cogenerator is given by $\\mathbb{R} \\cup \\{\\infty\\}$ with the metric in which $d(a,\\infty)=\\infty$ for $a \\in \\mathbb{R}$. Then one checks that the maps $d(a,-) : X \\to \\mathbb{R} \\cup \\{\\infty\\}$ are non-expansive and finishes as for $\\mathbf{Met}$.' },
		{ id: 'disjoint coproducts', reason: 'This easily follows from the corresponding fact for sets, since coproducts are built using disjoint unions.' },
	],
	'Met_c': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Met}_c \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'equalizers', reason: 'Just restrict the metric to the equalizer built from the sets.' },
		{ id: 'disjoint coproducts', reason: 'This easily follows from the corresponding fact for sets, since coproducts are built using disjoint unions.' },
		{ id: 'well-powered', reason: 'follows easily from the fact that monomorphisms here are injective' },
		{ id: 'generator', reason: 'The one-point metric space is a generator since it represents the forgetful functor $\\mathbf{Met}_c \\to \\mathbf{Set}$.' },
		{ id: 'cogenerator', reason: 'The same proof as for $\\mathbf{Met}$ shows that $\\mathbb{R}$ with the usual metric is a cogenerator.' },
		{ id: 'infinitary distributive', reason: 'This follows from the corresponding fact for topological spaces.' },
		{ id: 'countable products', reason: "For finite products, we take the cartesian product with, say, the sup-metric. The prouct of countably many metric spaces $(X_i,d_i)_{i \\geq 0}$ is given by the cartesian product $\\prod_{i \\geq 0} X_i$ with the metric $d(x,y) := \\sum_{i \\geq 0} d_i(x_i,y_i)/(1 + d_i(x_i,y_i))$. See Engelking's book <i>General Topoloy</i>." },
	],
	'Ban': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Ban} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'pointed', reason: 'The trivial Banach space $\\{0\\}$ is a zero object.' },
		{ id: 'locally ℵ₁-presentable', reason: 'Example 1.48 in <a href="https://ncatlab.org/nlab/show/Locally+Presentable+and+Accessible+Categories" target="_blank">Adamek-Rosicky</a>.' },
		{ id: 'disjoint coproducts', reason: 'This follows from the corresponding fact for topological spaces, since the coproduct is built from the direct sum of vector spaces (using the $1$-norm).' },
		{ id: 'cogenerator', reason: 'Hahn-Banach shows that $\\mathbb{C}$ is a cogenerator.' },
	],
	'Man': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Man} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'well-powered', reason: 'follows from the fact that monomorphisms are injective here' },
		{ id: 'distributive', reason: 'This follows from the corresponding fact for topological spaces.' },
		{ id: 'generator', reason: 'The $0$-dimensional one-point manifold is a generator since it represents the forgetful functor $\\mathbf{Top} \\to \\mathbf{Set}$.' },
		{ id: 'disjoint finite coproducts', reason: 'This follows from the corresponding fact for topological spaces.' },
		{ id: 'countable coproducts', reason: 'Take the usual disjoint union, which is clearly a smooth manifold, still second-countable. (Without that condition, all coproducts would exist.)' },
		{ id: 'Cauchy complete', reason: 'See Theorem 2.1 at the <a href="https://ncatlab.org/nlab/show/smooth+manifold" target="_blank">nLab</a>.' },
	],
	'Meas': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Meas} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'well-powered', reason: 'follows from the fact that monomorphisms are injective here' },
		{ id: 'well-copowered', reason: 'follows from the fact that epimorphisms are surjective here' },
		{ id: 'complete', reason: 'Take the limit of the underlying sets and take the smallest $\\sigma$-algebra making all projections measurable.' },
		{ id: 'cocomplete', reason: 'Take the colimit of the underlying sets and take the largest $\\sigma$-algebra making all inclusions measurable. That is, a set is measurable iff its preimage under each inclusion is measurable.' },
		{ id: 'infinitary distributive', reason: 'We need to check that the canonical bijective measurable map $\\coprod_i X \\times Y_i \\to X \\times \\coprod_i Y_i$ maps measurable sets onto measurable sets. By the description of measurable sets in a disjoint union, it suffices to prove that each $X \\times Y_i \\to X \\times \\coprod_i Y_i$ maps measurable sets onto measurable sets. So it suffices to prove that $f : X \\times Y \\to X \\times (Y + Z)$ does that. Using that $f$ is injective and that $f(X \\times Y)$ is measurable, it follows that the subsets of $X \\times Y$ that are mapped to a measurable set via $f$ form a $\\sigma$-algebra. But the $\\sigma$-algebra of $X \\times Y$ is generated by sets of the form $U \\times V$ for measurable subsets $U,V$, and their $f$-images are clearly measurable.' },
		{ id: 'generator', reason: 'The one-point measurable space (with the unique $\\sigma$-algebra) is a generator since it represents the forgetful functor $\\mathbf{Meas} \\to \\mathbf{Set}$.' },
		{ id: 'cogenerator', reason: 'Take the two-element set $2$ endowed with the trivial $\\sigma$-algebra (where only $\\emptyset$ and $2$ are measurable), and use that $2$ is a cogenerator for $\\mathbf{Set}$.' },
		{ id: 'disjoint coproducts', reason: 'This follows easily from the corresponding fact for sets, since coproducts are built using disjoint unions here.' },
	],
	'N': [
		{ id: 'small', reason: 'trivial' },
		{ id: 'thin', reason: 'trivial' },
		{ id: 'finitely cocomplete', reason: 'Finitely many natural numbers have a supremum natural number.' },
		{ id: 'binary products', reason: 'Two natural numbers have a minimum.' },
		{ id: 'connected limits', reason: 'Every non-empty set of natural numbers has a minimum.' },
		{ id: 'skeletal', reason: 'The relation $\\leq$ is antisymmetric.' },
	],
	'Cat': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Cat} \\to \\mathbf{Set} \\times \\mathbf{Set}$, $\\mathcal{C} \\mapsto (\\mathrm{Ob}(\\mathcal{C}),\\mathrm{Mor}(\\mathcal{C}))$, and $\\mathbf{Set} \\times \\mathbf{Set}$ is locally small.' },
		{ id: 'cartesian closed', reason: 'See p. 98 in <a href="https://ncatlab.org/nlab/show/Categories+for+the+Working+Mathematician" target="_blank">Mac Lane</a>.' },
		{ id: 'locally finitely presentable', reason: 'See <a href="https://mathoverflow.net/questions/84460" target="_blank">MO/84460</a>.' },
		{ id: 'disjoint coproducts', reason: 'This follows easily from the description of a coproduct of categories (based on disjoint unions).' },
	],
	'On': [
		{ id: 'locally small', reason: 'trivial' },
		{ id: 'thin', reason: 'trivial' },
		{ id: 'cocomplete', reason: 'Every set of ordinal numbers has a supremum.' },
		{ id: 'binary products', reason: 'For ordinal numbers $\\alpha,\\beta$ their minimum exists, it is $\\alpha$ when $\\alpha \\leq \\beta$ and $\\beta$ otherwise.' },
		{ id: 'connected limits', reason: 'Every non-empty set of ordinal numbers has a minimum.' },
		{ id: 'well-powered', reason: 'This is because for every ordinal $\\alpha$ the collection of ordinals $\\leq \\alpha$ is a set (namely, $\\alpha + 1$).' },
		{ id: 'skeletal', reason: 'The relation $\\leq$ is antisymmetric.' },
	],
	'LRS': [
		{ id: 'locally small', reason: 'For two ringed spaces $(X,O_X)$, (Y,O_Y)$, the collection of morphisms $X \\to Y$ of ringed spaces is the collection $\\prod_{f \\in \\hom(X,Y)} \\hom(O_Y,f_* O_X)$, which is a set since $\\hom(X,Y)$ is a set and each $\\hom(O_Y,f_* O_X)$ is a set.' },
		{ id: 'complete', reason: 'See <a href="https://arxiv.org/abs/1103.2139" target="_blank">Localization of ringed spaces</a> by W. Gillam. See also <a href="https://math.stackexchange.com/questions/1033675" target="_blank">MSE/1033675</a>.' },
		{ id: 'cocomplete', reason: 'Demazure-Gabriel\'s "Groupes algébriques", I. §1. 1.6' },
		{ id: 'well-powered', reason: '' },
		{ id: 'well-copowered', reason: '' },
		{ id: 'infinitary distributive', reason: 'See <a href="https://math.stackexchange.com/questions/5036488/" target="_blank">MSE/5036488</a>.' },
		{ id: 'disjoint coproducts', reason: '' },
	],
	'Sch': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Sch} \\to \\mathbf{LRS}$ and $\\mathbf{LRS}$ is locally small.' },
		{ id: 'finitely complete', reason: '' },
		{ id: 'well-powered', reason: '' },
		{ id: 'infinitary distributive', reason: 'This follows from the corresponding fact for locally ringed spaces, see <a href="https://math.stackexchange.com/questions/5036488/" target="_blank">MSE/5036488</a>.' },
		{ id: 'disjoint coproducts', reason: '' },
	],
	'Fld': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Fld} \\to \\mathbf{Set}$ and $\\mathbf{Set}$ is locally small.' },
		{ id: 'filtered colimits', reason: 'Consider a filtered diagram $(F_i)$ of fields and take the colimit $F$ in the category of commutative rings. Now one checks that $F$ is a field as well, and the universal property remains true for fields.' },
		{ id: 'connected limits', reason: 'Consider a connected diagram $(F_i)$ of fields and take the limit $F$ in the category of commutative rings. Now one checks that $F$ is a field as well, and the universal property remains true for fields. Namely, $1 = 0$ in $F$ would imply that $1 = 0$ in each $F_i$ and hence, since the diagram is connected, in some $F_i$, which is a contradiction. And if $x \\in F$ is non-zero, then all components $x_i$ are non-zero and hence invertible: Choose some $j$ such that $x_j$ is non-zero. Since there is a zig zag path of morphisms between $i$ and $j$ in the index category, which get mapped to field homomorphisms which are injective, it follows that $x_i$ is non-zero.' },
		{ id: 'inhabited', reason: 'trivial' },
		{ id: 'left cancellative', reason: 'It is well-known that every field homomorphism is injective and hence a monomorphism.' },
		{ id: 'well-powered', reason: 'The subfields of a given field form a set.' },
	],
	'FreeAb': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{FreeAb} \\to \\mathbf{Set}$ and $\\mathbf{Ab}$ is locally small.' },
		{ id: 'additive', reason: 'follows easily from the facts for abelian groups' },
		{ id: 'coproducts', reason: 'free abelian groups are closed under direct sums of abelian groups' },
		{ id: 'well-powered', reason: 'This is clear since the monomorphisms are injective.' },
		{ id: 'well-copowered', reason: 'See <a href="https://math.stackexchange.com/questions/5025660" target="_blank">MSE/5025660</a>.' },
		{ id: 'equalizers', reason: 'Subgroups of free abelian groups are free abelian.' },
		{ id: 'generator', reason: 'As for $\\mathbf{Ab}$, the group $\\mathbb{Z}$ is a generator.' },
		{ id: 'cogenerator', reason: 'It is easy to check that $\\mathbb{Z}$ is a cogenerator for free abelian groups.' },
		{ id: 'Malcev', reason: 'follows in the same way as for abelian groups' },
	],
	'Z': [
		{ id: 'complete', reason: 'follows immediately from the fact for $\\mathbf{Set}$' },
		{ id: 'cocomplete', reason: 'follows immediately from the fact for $\\mathbf{Set}$' },
		{ id: 'infinitary distributive', reason: 'follows immediately from the fact for $\\mathbf{Set}$' },
		{ id: 'exact filtered colimits', reason: 'follows immediately from the fact for $\\mathbf{Set}$' },
		{ id: 'disjoint coproducts', reason: 'follows immediately from the fact for $\\mathbf{Set}$' },
		{ id: 'mono-regular', reason: 'follows immediately from the fact for $\\mathbf{Set}$' },
		{ id: 'epi-regular', reason: 'follows immediately from the fact for $\\mathbf{Set}$' },
	],
	'BG': [
		{ id: 'small', reason: 'trivial' },
		{ id: 'groupoid', reason: 'trivial' },
		{ id: 'connected', reason: 'trivial' },
		{ id: 'generator', reason: 'The unique object is a generator for trivial reasons.' },
		{ id: 'skeletal', reason: 'There is just one object.' },
	],
	'BGf': [
		{ id: 'finite', reason: 'trivial' },
		{ id: 'groupoid', reason: 'trivial' },
		{ id: 'connected', reason: 'trivial' },
		{ id: 'generator', reason: 'The unique object is a generator for trivial reasons.' },
		{ id: 'skeletal', reason: 'There is just one object.' },
	],
	'BN': [
		{ id: 'small', reason: 'trivial' },
		{ id: 'connected', reason: 'trivial' },
		{ id: 'self-dual', reason: 'The identity is a self-duality since the addition is commutative.' },
		{ id: 'generator', reason: 'The unique object is a generator for trivial reasons.' },
		{ id: 'pullbacks', reason: 'For natural numbers $n,m$ we need to find a universal pair $p,q$ of natural numbers satisfying $n + p = m + q$. We may assume w.l.o.g. $n \\leq m$. Then take $p = m-n$, $q = 0$.' },
		{ id: 'left cancellative', reason: 'This is because addition of natural numbers is cancellative.' },
		{ id: 'skeletal', reason: 'There is just one object.' },
	],
	'walking_pair': [
		{ id: 'finite', reason: 'trivial' },
		{ id: 'self-dual', reason: 'trivial' },
		{ id: 'connected', reason: 'trivial' },
		{ id: 'generator', reason: 'It is easy to check that $0$ is a generator.' },
		{ id: 'filtered colimits', reason: 'Every filtered diagram can be reduced to one of the three trivial diagrams $0 \\to 0$, $0 \\to 1$, $1 \\to 1$, which have colimits $0$, $1$, resp. $1$.' },
		{ id: 'left cancellative', reason: 'The two morphisms $0 \\to 1$ are clearly monomorphisms.' },
		{ id: 'skeletal', reason: 'The two objects are not isomorphic.' },
	],
	'walking_isomorphism': [
		{ id: 'trivial', reason: 'The inclusion $\\{0\\} \\hookrightarrow \\{0 \\to 1\\}$ is clearly an equivalence.' },
		{ id: 'finite', reason: 'trivial' },
	],
	'Setne': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{Set}_{\\neq \\emptyset} \\to \\mathbf{Set}$ and $\\mathbf{Ab}$ is locally small.' },
		{ id: 'generator', reason: 'The one-point set is clearly a generator.' },
		{ id: 'cogenerator', reason: 'The two-point set is a cogenerator, this follows as for $\\mathbf{Set}$.' },
		{ id: 'well-powered', reason: 'This follows from the description of monomorphisms as injective functions.' },
		{ id: 'well-copowered', reason: 'This follows from the description of epimorphisms as surjective functions.' },
		{ id: 'products', reason: 'Take the product of non-empty sets inside of $\\mathbf{Set}$ and observe that it is non-empty by the axiom of choice.' },
		{ id: 'wide pushouts', reason: 'The wide pushout taken in $\\mathbf{Set}$ is clearly non-empty, and it still satisfies the universal property.' },
		{ id: 'coequalizers', reason: 'The coequalizer taken in $\\mathbf{Set}$ is clearly non-empty, and it still satisfies the universal property.' },
		{ id: 'cartesian closed', reason: 'This follows as for $\\mathbf{Set}$, since for non-empty sets $X,Y$ there is at least one function $X \\to Y$.' },
		{ id: 'mono-regular', reason: 'This follows as for $\\mathbf{Set}$.' },
		{ id: 'epi-regular', reason: 'This follows as for $\\mathbf{Set}$.' },
	],
	'B': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbb{B} \\to \\mathbf{Set}$ and $\\mathbf{Ab}$ is locally small.' },
		{ id: 'essentially small', reason: 'Every finite set is isomorphic to some $[n] = \\{1,\\dotsc,n\\}$ for some $n \\in \\mathbb{N}$.' },
		{ id: 'groupoid', reason: 'trivial' },
		{ id: 'inhabited', reason: 'trivial' },
	],
	'FI': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{FI} \\to \\mathbf{Set}$ and $\\mathbf{Ab}$ is locally small.' },
		{ id: 'initial object', reason: 'Take the empty set.' },
		{ id: 'left cancellative', reason: 'trivial' },
		{ id: 'essentially small', reason: 'Every finite set is isomorphic to some $[n] = \\{1,\\dotsc,n\\}$ for some $n \\in \\mathbb{N}$.' },
		{ id: 'generator', reason: 'The one-point set is a generator since it represents the forgetful functor $\\mathbf{FI} \\to \\mathbf{Set}$.' },
		{ id: 'connected limits', reason: '' },
		{ id: 'mono-regular', reason: '' },
		{ id: 'epi-regular', reason: '' },
	],
	'FS': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{FS} \\to \\mathbf{Set}$ and $\\mathbf{Ab}$ is locally small.' },
		{ id: 'essentially small', reason: 'Every finite set is isomorphic to some $[n] = \\{1,\\dotsc,n\\}$ for some $n \\in \\mathbb{N}$.' },
		{ id: 'right cancellative', reason: 'trivial' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'wide pushouts', reason: '' },
		{ id: 'coequalizers', reason: '' },
		{ id: 'mono-regular', reason: '' },
		{ id: 'epi-regular', reason: '' },
	],
	'BOn': [
		{ id: 'connected', reason: 'trivial' },
		{ id: 'generator', reason: 'There is just one object.' },
		{ id: 'cogenerator', reason: 'There is just one object.' },
		{ id: 'left cancellative', reason: 'It is well-known that ordinal addition satisfies $\\alpha + \\beta = \\alpha + \\gamma \\implies \\beta = \\gamma$.' },
		{ id: 'well-copowered', reason: 'This follows from the description of epimorphisms as finite ordinals, see <a href="https://math.stackexchange.com/questions/5029605" target="_blank">MO/5029605</a>.' },
		{ id: 'equalizers', reason: 'See <a href="https://math.stackexchange.com/questions/5029668/" target="_blank">MSE/5029668</a>.' },
		{ id: 'skeletal', reason: 'There is just one object.' },
	],
	'FinOrd': [
		{ id: 'locally small', reason: 'There is a forgetful functor $\\mathbf{FinOrd} \\to \\mathbf{Set}$ and $\\mathbf{Ab}$ is locally small.' },
		{ id: 'essentially small', reason: 'Every finite order is isomorphic to $\\{1 < \\cdots < n \\}$ for some $n \\in \\mathbb{N}$.' },
		{ id: 'finitely complete', reason: '' },
		{ id: 'generator', reason: 'The one-point finite order is a generator since it represents the forgetful functor $\\mathbf{FinOrd} \\to \\mathbf{Set}$.' },
		{ id: 'cogenerator', reason: '' },
		{ id: 'strict initial object', reason: 'The empty order is initial and is clearly strict.' },
		{ id: 'coequalizers', reason: '' },
		{ id: 'mono-regular', reason: '' },
		{ id: 'epi-regular', reason: '' },
	],
	'Rel': [
		{ id: 'locally small', reason: 'The set of morphisms $X \\to Y$ is the set $P(X \\times Y)$.' },
		{ id: 'self-dual', reason: 'There is an isomorphism $\\mathbf{Rel} \\to \\mathbf{Rel}^{\\mathrm{op}}$ that is the identity on objects (sets) and maps a relation $R \\subseteq X \\times Y$ to the opposite relation $R^o \\subseteq Y \\times X$ defined by $R^o := \\{(y,x) : (x,y) \\in R \\}$.' },
		{ id: 'pointed', reason: 'The empty set is clearly both initial and terminal.' },
		{ id: 'generator', reason: 'One checks that the the one-point set is a generator.' },
		{ id: 'disjoint coproducts', reason: 'It is an easy exercise to deduce this from the corresponding fact for sets and that sets form a distributive category.' },
		{ id: 'well-powered', reason: 'Any relation $R : A \\to B$ induces an injective map $P(A) \\to P(B)$, so that in particular there is an injective map $A \\to P(B)$.' },
	],
	'Sp': [
		{ id: 'essentially small', reason: 'This holds because $\\mathbf{FinSet}$ and $\\mathbb{B}$ are essentially small.' },
		{ id: 'finitely complete', reason: 'This follows from the corresponding fact for $\\mathbf{FinSet}$.' },
		{ id: 'finitely cocomplete', reason: 'This follows from the corresponding fact for $\\mathbf{FinSet}$.' },
		{ id: 'mono-regular', reason: 'This follows from the corresponding fact for $\\mathbf{FinSet}$ since there every monomorphism is even effective.' },
		{ id: 'epi-regular', reason: 'This follows from the corresponding fact for $\\mathbf{FinSet}$ since there every epimorphism is even effective.' },
		{ id: 'distributive', reason: 'This follows from the corresponding fact for $\\mathbf{FinSet}$.' },
		{ id: 'disjoint finite coproducts', reason: 'This follows from the corresponding fact for $\\mathbf{FinSet}$.' },
	],
	'real_interval': [
		{ id: 'small', reason: 'trivial' },
		{ id: 'self-dual', reason: 'Take $t \\mapsto 1-t$.' },
		{ id: 'distributive', reason: '' },
		{ id: 'locally ℵ₁-presentable', reason: 'See <a href="https://math.stackexchange.com/questions/4481902/locally-presentable-vs-compactly-presentable-categories#comment9399784_4482185" target="_blank">MSE/4481902</a>.' },
		{ id: 'skeletal', reason: 'The relation $\\leq$ is antisymmetric.' },
	],
	'Zdiv': [
		{ id: 'small', reason: 'trivial' },
		{ id: 'products', reason: 'Take the $\\gcd$ of a subset.' },
		{ id: 'distributive', reason: 'Using prime factorizations, one can prove that $\\gcd(a, \\mathrm{lcm} \\{b_i \\}) = \\mathrm{lcm} \\{ \\gcd(a, b_i) \\}$ for finitely many $b_i$.' },
		{ id: 'locally ℵ₁-presentable', reason: 'Every $\\aleph_1$-directed diagram is eventually constant.' },
	],
	'Noo': [
		{ id: 'small', reason: 'trivial' },
		{ id: 'coproducts', reason: 'Take the supremum.' },
		{ id: 'skeletal', reason: 'The relation $\\leq$ is antisymmetric' },
		{ id: 'infinitary distributive', reason: 'One can show that $\\sup_i \\min(a,b_i) = \\min(a, \\sup_i b_i)$.' },
		{ id: 'locally finitely presentable', reason: 'Every natural number is finitely presentable, and $\\infty$ is the colimit of all $n < \\infty$.' },
	],
}
