name: preview deployment
on:
    workflow_dispatch:

jobs:
    call-deploy:
        uses: ./.github/workflows/_deploy-reusable.yaml
        permissions:
            contents: write
        with:
            is_prod: false
            skip_db: false
        secrets:
            CATDAT_DB_URL: ${{ secrets.CATDAT_DB_PREVIEW_URL }}
            CATDAT_DB_AUTH_TOKEN: ${{ secrets.CATDAT_DB_PREVIEW_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
            APP_DB_URL: ${{ secrets.APP_DB_URL }}
            APP_DB_AUTH_TOKEN: ${{ secrets.APP_DB_AUTH_TOKEN }}
            _GITHUB_PRIVATE_KEY: ${{ secrets._GITHUB_PRIVATE_KEY }}
            REDIS_URL: ${{ secrets.REDIS_URL }}
            ADMIN_PAGE_PASSWORD: ${{ secrets.ADMIN_PAGE_PASSWORD }}
            EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            ENABLE_EMAILS: ${{ secrets.ENABLE_EMAILS }}
            APPROVAL_EMAIL: ${{ secrets.APPROVAL_EMAIL }}
